version: '3'

services:

  server:
    build: ./server
    expose:
      - 3002
    ports:
      - 3002:3002
    command: node app.js

  client:
    build:
      context: ./client
      args:
        REACT_APP_HOST: 192.168.0.83

    expose:
      - 8080
    ports:
      - 8080:8080
