version: '3'

services:

  server:
    build: ./server
    container_name: ws_server
    expose:
      - 3002
    ports:
      - 3002:3002
    command: node app.js

  client:
    build: ./client
    environment:
      - REACT_APP_HOST=ws_server
    expose:
      - 3001
    ports:
      - 3001:3001
    command: npx http-server build -p 3001
