version: '3'

services:

  server:
    build: ./server
    container_name: ws_server
    expose:
      - 3002
    ports:
      - 3002:3002
    command: node app.js

  client:
    build: ./client
    environment:
      - REACT_APP_HOST1=ws_server
      - REACT_APP_HOST=${ws_server}
      - REACT_APP_HOST2=http://192.168.0.83
    expose:
      - 3001
    ports:
      - 3001:3001
    links:
      - server
    command: npx http-server build -p 3001
