version: '3'

services:

  server:
    build: ./server
    expose:
      - 3002
    ports:
      - 3002:3002
    command: node app.js

  client:
    build: ./client
    args:
      - REACT_APP_HOST:${REACT_APP_HOST}
    expose:
      - 3001
    ports:
      - 3001:3001
    command: npx http-server build -p 3001
